--[[
this file is auto-generated by Configer Tools
]]

return 
{{"id","name","designName","path","dpath","baseSpeed","speedRatio"},
{{1000,"AM","AM","Assets/Res/Prefabs/Avatar/Char_AM.prefab","Assets/Res/Prefabs/DungeonAvatar/Char_AM.prefab",5,{0.8,1.2}}
,{1001,"AS","AS","Assets/Res/Prefabs/Avatar/Char_AS.prefab","Assets/Res/Prefabs/DungeonAvatar/Char_AS.prefab",5,{0.8,1.2}}
,{2000,"Archimonde","Archimonde","Assets/Res/Prefabs/Avatar/Char_Archimonde.prefab","Assets/Res/Prefabs/DungeonAvatar/Char_Archimonde.prefab",5,{0.8,1.2}}
,{3000,"Clr1","Clr1","Assets/Res/Prefabs/Avatar/Char_Clr1.prefab","Assets/Res/Prefabs/DungeonAvatar/Char_Clr1.prefab",5,{0.8,1.2}}
}}