--[[
this file is auto-generated by Configer Tools
]]

return 
{{"id","name","designName","path","upOffset","downOffset"},
{{1,"Map001","Map001","Map001",{1.43,3},{-1.52,-2.2}}
,{2,"Map002","Map002","Map002",{1.43,3},{-1.52,-2.2}}
,{3,"Map003","Map003","Map003",{1.69,3},{-1.52,-2.2}}
}}