--[[
this file is auto-generated by Configer Tools
]]

return 
{{"id","name","designName","type","avatar","genericAtk","skills","view"},
{{1000,"AM","AM",1,1000,1000,{},3}
,{1001,"AS","AS",1,1001,1001,{},3}
,{2000,"Archimonde","Archimonde",2,2000,1201,{},3}
,{3000,"Clr1","Clr1",3,3000,1301,{},3}
}}