--[[
this file is auto-generated by Configer Tools
]]

return 
{{"id","name","designName","type","icon","melee","atkType","passive","prepareAnim","startAnim","loopAnim","endAnim","spell","bone","boneOffset"},
{{1000,"am_generic_attack","敌法普通攻击",1,"Icon_Skill1000",true,1,false,"","attack5","","",1000,"",configer_s1(0,0)}
,{1001,"as_generic_attack","小鹿普通攻击",1,"Icon_Skill1001",false,1,false,"","attack5","","",1000,"",configer_s1(0,0)}
,{1201,"archimonde_generic_attack","阿克蒙德普通攻击",1,"Icon_Skill1201",false,1,false,"","attack5","","",0,"",configer_s1(0,0)}
,{1301,"clr1_generic_attack","刀小狼怪普通攻击",1,"Icon_Skill1301",false,1,false,"","attack5","","",0,"",configer_s1(0,0)}
,{2000,"am_skill_1","瞬移",2,"Icon_Skill2000",true,3,false,"attack2_start","","","",0,"",configer_s1(0,0)}
}}